### ISSUE TITLE
Center everything so it looks professional™

### ISSUE THREAD

**Issue by Victor4X** [Scrumffed/scrumffed.github.io#2]
Center the two lines of text vertically and horizontally in relation to the whole page

**Comment by bmwasonga** [comment]
> Center the two lines of text vertically and horizontally in relation to the whole page

I have centred that for you
Check it out.

**Comment by Victor4X** [comment]
Hi Ben!
Thank you for your interest in the project :D
First of all, I would like you to submit a pull request with your changes, so they can be discussed properly.
Second, I think you have a typo in the header tag (`<h1'>` instead of `<h1>`),
And finally, I would like the text to be centered vertically as well, so maybe put both lines of text into a div, and center that as well?

**Comment by Victor4X** [comment]
I'm closing this issue as we rewrote the site (2f686348a4c0a281d6c904c1be3a215182a93fe0)
